version: "3.8"
services:
 server:
  image: nginx:latest
  ports:
  - 80:80
  volumes:
  - ./server/:/usr/share/nginx/html/
 client:
  build: client/
  command: python ./client.py
  network_mode: host
  depends_on:
  - server